#!/usr/bin/env tsx
/**
 * Build-time script: reads docs/rules/*.md from the repo root and generates
 * src/embedded-docs.ts so rule documentation ships inside the MCP package's
 * dist/ without relying on the unpublished docs/ directory.
 *
 * Run automatically via the `prebuild` and `prepare` npm scripts.
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, basename } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..", "..");
const DOCS_DIR = join(REPO_ROOT, "docs", "rules");
const OUTPUT_FILE = join(__dirname, "..", "src", "embedded-docs.ts");

async function main(): Promise<void> {
  const files = (await readdir(DOCS_DIR)).filter((f) => f.endsWith(".md"));

  const entries = await Promise.all(
    files.map(async (file) => {
      const ruleName = basename(file, ".md");
      const content = await readFile(join(DOCS_DIR, file), "utf8");
      return [ruleName, content] as const;
    }),
  );

  entries.sort(([a], [b]) => a.localeCompare(b));

  const lines = [
    "// AUTO-GENERATED by scripts/embed-rule-docs.ts — do not edit by hand.",
    "",
    "export const embeddedDocs: Record<string, string> = {",
    ...entries.map(
      ([name, content]) =>
        `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`,
    ),
    "};",
    "",
    `export const ruleNames: string[] = ${JSON.stringify(entries.map(([n]) => n))};`,
    "",
  ];

  await writeFile(OUTPUT_FILE, lines.join("\n"), "utf8");
  console.log("[embed-rule-docs] wrote rules to src/embedded-docs.ts", {
    count: entries.length,
  });
}

main().catch((err) => {
  console.error("[embed-rule-docs] failed:", err);
  process.exit(1);
});
